#!/bin/bash 
#SBATCH --job-name=cnvve_whisper_base_lora
#SBATCH --mail-type=ALL
#SBATCH --mail-user=msteams:marquez 
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH --time=48:00:00 
#SBATCH --partition=A100
#SBATCH --gpus=1g.20gb:1
#SBATCH --output=logs/cnvve/cnvve_whisper_base_lora.out
#SBATCH --qos=high

source .venv/bin/activate 
python -BO train.py experiments_configs/cnvve/whisper_base_lora.py