#!/bin/bash 
#SBATCH --job-name=donateacry_wavlm_base_plus_lora
#SBATCH --mail-type=ALL
#SBATCH --mail-user=msteams:marquez 
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH --time=48:00:00 
#SBATCH --partition=RTX
#SBATCH --gpus=2080ti:1
#SBATCH --output=logs/donateacry/donateacry_wavlm_base_plus_lora.out
#SBATCH --qos=high

source .venv/bin/activate 
python -BO train.py experiments_configs/donateacry/wavlm_base_plus_lora.py