#!/bin/bash 
#SBATCH --job-name=donateacry_wav2vec2_base_lora
#SBATCH --mail-type=ALL
#SBATCH --mail-user=msteams:dasaro 
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH --time=48:00:00 
#SBATCH --partition=RTX
#SBATCH --gpus=1
#SBATCH --output=logs/donateacry/donateacry_wav2vec2_base_lora.out

source .venv/bin/activate 
python -BO train.py experiments_configs/donateacry/wav2vec2_base_lora.py