#!/bin/bash


sbatch jobs/nonverbal_vocalization_dataset/nonverbal_vocalization_dataset_whisper_tiny_frozen.job
sbatch jobs/asvp_esd/asvp_esd_whisper_tiny_frozen.job
sbatch jobs/vivae/vivae_whisper_tiny_frozen.job
sbatch jobs/cnvve/cnvve_whisper_tiny_frozen.job
sbatch jobs/recanvo/recanvo_whisper_tiny_frozen.job