#!/bin/bash

sbatch jobs/donateacry/donateacry_wavlm_base_plus_frozen.job
sbatch jobs/donateacry/donateacry_hubert_base_lora.job
sbatch jobs/donateacry/donateacry_wavlm_base_plus_lora.job
sbatch jobs/donateacry/donateacry_hubert_base_frozen.job
sbatch jobs/donateacry/donateacry_whisper_base_lora.job
sbatch jobs/donateacry/donateacry_wav2vec2_base_lora.job
sbatch jobs/donateacry/donateacry_whisper_base_frozen.job
sbatch jobs/donateacry/donateacry_wav2vec2_base_frozen.job
