#!/bin/bash 
#SBATCH --job-name=recanvo_whisper_base_lora
#SBATCH --mail-type=ALL
#SBATCH --mail-user=msteams:marquez 
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH --time=48:00:00 
#SBATCH --partition=RTX
#SBATCH --gpus=2080ti:1
#SBATCH --output=logs/recanvo/recanvo_whisper_base_lora.out
#SBATCH --qos=high

source .venv/bin/activate 
python -BO train.py experiments_configs/recanvo/whisper_base_lora.py