#!/bin/bash 
#SBATCH --job-name=asvp_esd_wav2vec2_base_lora
#SBATCH --mail-type=ALL
#SBATCH --mail-user=msteams:marquez 
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH --time=48:00:00 
#SBATCH --partition=A100
#SBATCH --gpus=3g.40gb:1
#SBATCH --output=logs/asvp_esd/asvp_esd_wav2vec2_base_lora.out
#SBATCH --qos=high

source .venv/bin/activate 
python -BO train.py experiments_configs/asvp_esd/wav2vec2_base_lora.py